### ISSUE TITLE
Unable to deserialize HashSet<T>

### ISSUE THREAD

**Issue by niemyjski** [kevin-montrose/Jil#105]
I'm unable to deserialize HashSets with Jil:

        public class HashSetTest
        {
            public HashSetTest() {
                Tags = new HashSet<string>();
            }

            public HashSet<string> Tags { get; set; }
        }

Exception:

      Jil.DeserializationExceptionExpected: {, null
         at _DynamicMethod1(TextReader, Int32)
         at Jil.JSON.Deserialize(TextReader reader, Options options) in c:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs: line 972
         at Jil.JSON.Deserialize(String text, Options options) in c:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs: line 997

**Comment by kevin-montrose** [comment]
This is by design, Jil will deserialize a list to anything that implements [`IList<T>`](http://msdn.microsoft.com/en-us/library/5y536ey6%28v=vs.110%29.aspx) which [`HashSet<T>`](http://msdn.microsoft.com/en-us/library/bb359438%28v=vs.110%29.aspx) does not.  [Supported types are mentioned in the README.](https://github.com/kevin-montrose/Jil#supported-types)

As to *why* this is... JSON doesn't have a notion of a unique set of elements, and it's lists/arrays are ordered.  It would make me nervous to have Jil change the order of elements in an array when serializing a deserialized bit of JSON.

**Comment by niemyjski** [comment]
This prevents us from ever using this library... HashSet implements ISet, and ISet is unordered, it just can't have duplicate values in it.. ( http://msdn.microsoft.com/en-us/library/dd412081%28v=vs.110%29.aspx ). A sorted set will handle sorting the data as you put into it.. So deserializing that without worrying shouldn't be a problem..

**Comment by niemyjski** [comment]
If you are worried about duplicate data then let the runtime throw the error. If the user wants to put garbage in, he can get an error out.

**Comment by clipperhouse** [comment]
JSON doesn’t have a notion of uniqueness, so it’s logically out of scope for a deserializer.

Implementing a ToHashSet on the caller side is trivial: http://stackoverflow.com/questions/3471899/how-to-convert-linq-results-to-hashset-or-hashedset

**Comment by niemyjski** [comment]
Yeah, I understand what your saying.. But why not try to deserialize the array to it and if it blows up for non uniqueness than its not your (Jils) problem but the user for giving it garbage. For example I want to use jil to serialize my object that has a hashset and put it into redis cache.. Getting it out I know its unique.

**Comment by clipperhouse** [comment]
I think from a design perspective (not to put words in Kevin’s mouth), it becomes Jil’s problem because this would be asking it to do something more heuristic that deterministic. It introduces a new class of error.

A JSON deserializer should handle things that have clear representations or analogs in JSON. Hashsets do not. So, let the caller decide.

Jil’s handling of dates is analogous. It requires the caller specify exactly what date format to understand – Jil doesn’t get into “trying” to figure it out. Too heuristic. If one wants to parse dates heuristically, the caller can implement their own logic.

**Comment by niemyjski** [comment]
I don't mean to be a PITA... I guess I don't understand why this is such a problem (even though I understand what you are saying). Why do you support ICollection or IList<T>? Shouldn't you only support T[]? My thought is you would just to do the conversion and under the hood it would call TryConvert on the type or something?

By the way a HashSet of String is serialized as ["My", "String", "Array"]

**Comment by bretcope** [comment]
@niemyjski fyi, this is now supported via #219 and released as 2.14.0.

**Comment by niemyjski** [comment]
Thank you!!!!
