### ISSUE TITLE
Jil Deserializer failes to convert int and string data from JSON to object

### ISSUE THREAD

**Issue by ravi032** [kevin-montrose/Jil#114]
I have observed that Jil fails to convert int and string data from JSON to object.

Lets say I have a model class,

class Employee
{
   public int Id
   public string Name
}

And my Json Data => {"id":"1","Name":Ravi}

When I use => var obj = JSON.Deserialize<Employee>( {"id":"1","Name":Ravi});

Result will be an exception.

The reason I find is, For int type, value should not be with quotation mark and for string type value should be within quotation mark. 

Please correct me if my understanding is not correct?

In servicestack.Text, I did not see this issue.

**Comment by kevin-montrose** [comment]
Jil is strict with type matching, and will not coerce between string and int (or double, etc.).  This is by design.

This is a speed trade-off, if Jil coerced it would necessarily be slower to account for the additional checks at runtime.

In order to deserialize to that model, your JSON must be of the form `{"Id": 1, "Name": "Ravi"}`.
