### ISSUE TITLE
Dictionary with DateTime as key is not supported

### ISSUE THREAD

**Issue by milindur** [kevin-montrose/Jil#121]
The serialization/deserialization of dictionaries is currently only possible with strings, numbers, or enums as keys. For transfering time-based data (e.g. for charts) I also need DateTime as key of the dictionary.

As long as I use the ISO8601 oder (milli-)seconds since unix epoch as date format a DateTime-key could be serialized as string or (quoted) number. Only the Newtonsoft-style milliseconds since unix epoch are a problem, since these would be serialized as Date-object, which would not be possible because the key gets the member/property name of the JSON object.

So I think DateTime as key of a dictionary should be possible as long as the date-format is not the Newtonsoft-style.

What do you think? Did I overlook something?

I am currently experimenting with a modified version of Jil which supports the scenario described above. With some additional cleanup and after extending the unit-tests for this new feature I could provide a PR for this.

**Comment by kevin-montrose** [comment]
`DateTimes` aren't supported as dictionary keys because they can't always be represented properly to be valid JSON.

Only Newtonsoft and ISO8601 styles are strings (a requirement for an object key, since as a rule Jil does not do implicit conversions [string-to-int-to-DateTime in the other `DateTimeFormat` cases]), I'm disinclined to make which type graphs are legal vary by the `Options` passed in.  That seems very counter-intuitive, and really really brittle for consumers.

Even if that weren't the case, the string-y `DateTimes` still make bad keys since they don't roundtrip with [Tick](https://msdn.microsoft.com/en-us/library/system.datetime.ticks%28v=vs.110%29.aspx) granularity.  Newtonsoft-style is particular bad for that since it's only represented at millisecond granularity, but ISO8601 can also fail to roundtrip due to floating point rounding.  If Jil allowed these two `DateTime`s as keys, documentation would have to warn against *looking up* by key in a Dictionary which just feels wrong.

For time series data, I would instead suggest an array of objects.  This also has the benefit of being ordered, unlike a Dictionary, so the producer could force the events to be in the correct order for consumers.
