### ISSUE TITLE
Date / time serialization concerns

### ISSUE THREAD

**Issue by mj1856** [kevin-montrose/Jil#129]
Hi.  I just stumbled across Jil, and thought I would check out how it manages date and time issues - as that is one of my areas of specialty.

In general, it looks fairly good, except for a few things.

- The `MicrosoftStyleMillisecondsSinceUnixEpoch` option never encodes the offset. It should for a `DateTimeOffset`.
  - Ex. `2007-12-28T23:11:57.056-07:00` should be encoded as `"/Date(1198908717056-0700)/"`

- I highly recommend revisiting #80.  ISO8601 should be the default.

- The `UnspecifiedDateTimeKindBehavior` option only has two choices `IsUTC` or `IsLocal`.  There's no way to serialize an unspecified `DateTime` in its current representation.

  Consider:

        var options = new Options(dateFormat: DateTimeFormat.ISO8601);
        string json = JSON.Serialize(new DateTime(2015, 12, 31, 0, 0, 0), options);

  Since the `DateTime` has `Unspecified` kind, and the default option is `IsLocal`, and I'm in the US Pacific time zone, I get the output `"2015-12-31T08:00:00Z"`.

  If I explicitly set `IsUtc`, then I get `"2015-12-31T00:00:00Z"`.

  But what I *actually* want is `"2015-12-31T00:00:00"`.   This is a perfectly valid ISO-8601 string, and is the common convention for an unspecified `DateTime`.

  This is actually really important for a variety of use cases.  Consider an appointment scheduling system.  Mapping from a local time to UTC is sometimes unreliable for *future* dates, as time zone rules can be changed by governments.

- I don't really like the behavior of `Local` kind converting to UTC.  It has the unfortunate side effect of not being able to round-trip.  Other serializers (such as Newtonsoft) will serialize a local `DateTime` using the local offset.  So instead of getting `"2015-12-31T08:00:00Z"`, I would get `"2015-12-31T00:00:00-08:00"`.
 - On deserialization, if a value with an offset is deserialized to a `DateTime`, then the common convention is to convert to UTC using the offset in the string, then convert back to "local time" and mark it with `DateTimeKind.Local`.  (Though admittedly this is just convention - one might prefer to instead drop the offset and treat it as `DateTimeKind.Unspecified`.)

- You might just consider dropping the `UnspecifiedDateTimeKindBehavior` option entirely.  IMHO, it's not really needed, since the three kinds `Unspecified`, `Utc`, and `Local` will map cleanly if you take my previous two suggestions into consideration.

**Comment by kevin-montrose** [comment]
Your first point is reasonable, I will investigate it.  I vaguely recall some shenanigans around offsets being ignored with that format, so no promises.

I agree ISO8601 should be default, but I'm not going to change that in a point release.  Nor will I do a major release just to change it.  If and when 3.0 is created, I do intend to change the default.

---

For the rest, I disagree.  Unspecified `DateTimes` are a plague*, relying upon them is at best undesirable.  It's far too easy, in my experience, for code to make assumptions about time zones (either local or UTC) and make serious errors.  The BCL's behavior doesn't help.

Since the only `DateTimeKind` that is reliably transferable is UTC, that is what Jil converts to.  Any consumer who really needs to preserve time zone information should either use `DateTimeOffset`, or an additional field.

The `UnspecifiedDateTimeKindBehavior` configuration is aimed at cases where you can't control what sort of `DateTime` you are dealing with.  Ideally consumers would consciously be in Local or UTC, but this is not always possible (especially around ORMs).  In practice consumers appear to assume one or the other, the enum makes it easy to inform Jil which is being assumed.

To an extent Jil is looking at the world through Stack Overflow colored glasses**, and I do admit that not everyone thinks the same way.  When we deal with dates, we're dealing with dates across the entire world and UTC is the only realistic way to store and compare them.  That our serialization tends to prefer UTC is a natural consequence. 

*Note that [`DateTimeOffset`](https://msdn.microsoft.com/en-us/library/system.datetimeoffset%28v=vs.110%29.aspx) always assumes an offset.  There is no notion of "Unspecified".

**Although Jil is not officially a Stack Overflow / Stack Exchange library.

**Comment by mj1856** [comment]
Yeah, that ugly format does have some quirks.  I believe the shenanigan you're thinking of is that `DataContractJsonSerializer` has a bug where if an offset is present at all, it not only assumes local time (which is ok), but it doesn't adjust the date/time for that offset.  It just drops it and assumes the local offset instead.   (The `JavaScriptSerializer` doesn't have that particular bug.)

I agree that unspecified values can be difficult, but only when used inadvertently.  Common example is retrieving a `DateTime` from a DB and not setting it's kind.  But my point is that there are many use cases where you really DO want just a date and time, and pinning it to a particular time zone offset is not ideal.

Consider the use case of a simple date-of-birth.  Mine is `1976-08-27`.  .NET doesn't currently have a date-only data type out of the box.  One could use [Noda Time](http://nodatime.org)'s `LocalDate` type, or eventually perhaps [the one I'm working on](https://github.com/mj1856/corefx-dateandtime) will be part of the framework.  But for now, a SQL `date` type will get mapped to a .NET `DateTime`, with the time set to midnight, and the kind set unspecified.

When serialized as ISO8601, this *should* end up as `1976-08-27T00:00:00`  (again, I'd prefer `1976-08-27`, but that first needs type support).   If I treat unspecified as local and convert to UTC, it's serialized as `1976-08-27T07:00:00Z` in my time zone, but could be serialized as `1976-08-26T22:00:00Z` in another part of the world.  Suddenly my birthday could be a day early.  Serialized as UTC, `1976-08-27T00:00:00Z`, is no better, as it could still get adjusted to `1976-08-26T17:00:00` when converted back to my local time.

The reason that the date-of-birth case has this problem is because humans are intentionally ambiguous about pinning down the relevant time and time zone. They just don't apply in this context.  (See [my blog post on this subject](http://codeofmatt.com/2014/04/09/handling-birthdays-and-other-anniversaries/)).

WRT the StackOverflow colored glasses - I can see that you probably just have use cases where a date and time value represents an exact moment in time - such as recording the timestamp of a post.  But there are many other uses cases where that context doesn't apply.  See also [the four types of times](http://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices/3269325#3269325) (I disagree that there are only four, but the ones he describes are valid).

One thing I wasn't able to ascertain from the project readme - is Jil intented to be for general purpose? Or does it have specific intended usage where these other contexts aren't relevant?
