### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by crushglass** [kevin-montrose/Jil#134]
I have a json file like this

{
    "data": {        
        "id": "1",
        "name": null,
        "url": "http://www.google.com"
    }
}

I want to deserialize it to JilTest class

class JilTest
{
    [JilDirective("data")]
    public dynamic Data { get; set; }
}

I deserialize it like this
JilTest jilTest = Jil.JSON.Deserialize<JilTest>(json);

It works, but when I access jilTest.Data["name"] an exception throw as "Object reference not set to an instance of an object".

I try to deserialize it like
dynamic jilTest = Jil.JSON.DeserializeDynamic(json);

and access member jilTest["data"]["name"], it doesn't work also.

**Comment by Wazner** [comment]
I can reproduce this issue.

#### Findings
Only the accessor `Data["name"]` gives a `NullReferenceException` for null values, accessing it as a member `Data.name` works as expected (returns `null`)

```C#
var json = "{\"data\":{\"id\":\"1\",\"name\":null,\"url\":\"http://www.google.com\"}}";
var result = JSON.Deserialize<JilTest>(json); // or JSON.DeserializeDynamic(json);
// calling "result.Data.name" returns null here, as expected.
// calling "result.Data["name"]" throws a NullReferenceException
```

#### Code
The `TryGetMember` method in `JsonObject.Dynamic.cs` has an if statement that handles null values, on line 879.
```C#
if (val == null)
{
    result = null;
    return true;
}
```

But the `TryGetIndex` method does not. This causes an `NullReferenceException` to be thrown on line 826 in `JsonObject.Dynamic.cs` because `rawValue` will be `null`.
```C#
return rawValue.InnerTryConvert(returnType, out result);
```

#### Solution
@crushglass: For now, use the member access notation (e.g. `result.Data.name`) to access the value.

I think the behaviour of member access and index access should be the same. So I will make a pull request regarding this issue. But it's up to @kevin-montrose to give a final say if this is a bug or desired behaviour.
