### ISSUE TITLE
Deserializing properties have null values

### ISSUE THREAD

**Issue by scheepersw** [kevin-montrose/Jil#155]
Hi
I'm quite new to Json and I'm sure I'm just doing something wrong.  When I deserialise a simple type with four properties, Jil deserialises the properties but the values are null.  Could you point out where I'm going wrong?
// no inheritance
public class MyObject
{
  public string Validator { get; set; }
  public long Sequence { get; set; }
  public object Value { get; set; }
  public Dictionary<string, object> Parameters { get; set; }
}

and a sample of the Json string
{"validator":"AccountVerifiedAsyncAttribute","value":"asdf.","sequence":7,"parameters":null}

What I get back is a MyObject with;
validator = null
sequence = 0
value = null
parameters = null

and I call it like this with default parameters
MyObject myObj = Jil.JSON.Deserialize<MyObject>(json);

Thanks

**Comment by scheepersw** [comment]
BTW, I tested this with NewtonSoft's serializer to see if it will show me where I'm going wrong but it actually deserializes correctly.

**Comment by Wazner** [comment]
This is because Jil is case-sensitive. The properties of your C# class start with uppercase letters, but the keys in your JSON are all lowercase.

Jil does not support camelCasing yet, but support should be added soon, see #154.

For now you have 2 options:
1. Change the casing of either your C# properties or your JSON keys.
2. Use the `JilDirectiveAttribute` to specify a diffrent name for your C# properties.
You do this like so:
```C#
public class MyObject
{
    [JilDirective("validator")]
    public string Validator { get; set; }
    [JilDirective("sequence")]
    public long Sequence { get; set; }
    [JilDirective("value")]
    public object Value { get; set; }
    [JilDirective("parameters")]
    public Dictionary Parameters { get; set; }
}
```

**Comment by scheepersw** [comment]
I used the JilDirective and it works great. Thanks.
