### ISSUE TITLE
Serializing a List<BaseClass> return only field/properties of BaseClass

### ISSUE THREAD

**Issue by maurodx** [kevin-montrose/Jil#184]
I'm trying to serialize a List<BaseClass> but it contains CustomClass1 and CustomClass2 objects with this declaration:

public class CustomClass1: BaseClass{}
and
public class CustomClass2: BaseClass{}

I don't see CustomClass1/2 properties serialized in Json but only the BaseClass properties.

I'm serializing with

Jil.JSON.Serialize(element, Options.ISO8601IncludeInherited) for each element

**Comment by maurodx** [comment]
It works only with Jil.JSON.SerializeDynamic(element, Options.ISO8601IncludeInherited).

Do I lose performance in this case?

**Comment by kevin-montrose** [comment]
This is by design, as Jil's static serializer bakes types in at first call.  If `BaseClass` is the visible type at the call site, it's what gets baked in.

You lose a little perf using SerializeDynamic() because there's a lookup on the type in the dynamic serializer, but _most_ time will still be spent in the static serializer (once it figures out which type is present).  You can hint to Jil that less dynamic checking is needed by `sealed`-ing leaf types too, but I doubt that will matter in teh typical case.
