### ISSUE TITLE
Serialization bug when non-dynamically serializing a class with a property of type Object

### ISSUE THREAD

**Issue by ProVega** [kevin-montrose/Jil#195]
This is a bit hard to describe, but I ran into an issue that I have spent hours debugging.  I have a class "MyDetails" that has a property (it has a get and set) of type Object on it.  MyDetails.DefaultValue (Object).

When I serialize using this code:
JSON.Serialize<T>(valueToSerialize, Options.ExcludeNulls)

Where T is "Object" the .DefaultValue property properly serializes.

However if T is "MyDetails" (which is what valueToSerialize really is) the .DefaultValue property serializes as "{}".

I stepped through the code and it appears that SerializeDynamic doesn't has this problem, but the other branch of code does.  I stepped through and LoadToString in the static class builder appears to properly recognize the .DefaultValue property (which is of type Object) as a Property (vs a field) and it DOES invoke my getter on serialization.  But then it returns to WriteFormattingConstant and I can't make heads or tails of what it does with the value.  it seems to just skipper the value and write the outter { } bits.

**Comment by Wazner** [comment]
Jil is made for performance and because of this some things might not be as user-friendly as other serializers. 

When using the `Serialize` method, Jil only uses the type information known at compile time. So if a field is of type `object`, it will serialize the fields of `object` (which it doesn't have).

For your case, you need to use the `SerializeDynamic` method, this performs type checking every time an object is serialized.
