### ISSUE TITLE
Support for HJSON

### ISSUE THREAD

**Issue by MovGP0** [kevin-montrose/Jil#222]
It would be really interesting to expand JIL to support [HJSON](http://hjson.org/ ).

**Comment by bretcope** [comment]
The more loose the syntax is, the more you're going to pay a parsing penalty. Jil is built to be performant. Furthermore, it's built to be a performant _JSON_ parser, and HJSON is not JSON.

It looks to me like HJSON is primarily intended for human-generated files, like config files. How many times are you really going to parse a config file during an app's life cycle? Jil is actually a bad choice to begin with for something that you're only going to parse once because Jil has a lot of startup cost and then it keeps around a bunch of dynamically built code that's never going to be used again.

**Comment by MovGP0** [comment]
i can agree on that. so better use two libraries then.

**Comment by nathvi** [comment]
Why is this still open?
