### ISSUE TITLE
It throw exception "Expected dight" when there is a property named "checkCode" as request body

### ISSUE THREAD

**Issue by HelloJesse** [kevin-montrose/Jil#234]
LIke the form body is below 
{
"checkCode":"123"
}

It will throw exception "Expected digit"

**Comment by bretcope** [comment]
You're probably using a model which has `checkCode` as a numeric type. For example

```csharp
public class Test
{
    public int checkCode { get; set; }
}
```

In this case, your JSON won't work because `"123"` is a string, not a number, and Jil is pretty strict in its parsing rules (it won't call `int.Parse()` for you).

If you change `checkCode` in your model to be a `string`, it should parse just fine.
