### ISSUE TITLE
Deserializing array of arbitrary values

### ISSUE THREAD

**Issue by juho-hanhimaki** [kevin-montrose/Jil#273]
I am interested in deserializing arbitrary values contained in JSON array. The contents and data types inside the array may change anytime.

The objective is to deserialize data so it may be further processed and stored to disk using more effective serialization. The performance is key factor here, which brought me to investigate Jil.

Using Json.NET this can be achieved quite easily.

            string json = @"[1, true, 1.2345, null, ""test""]";
            var values = JsonConvert.DeserializeObject<object[]>(json);

Values array would then contain the values as .NET (boxed) primitive types (long, bool, double, object, string). The array would then be really easy to use for further processing and efficient storage.

However the Json.NET deserialization has quite large performance overhead.

Deserializing the same data with Jil seems to produce dynamic JsonObjects. I am having hard time figuring out what to do with the dynamic objects to get to the "raw" data. Is there feasible to way to achieve what I am trying to do using Jil?

**Comment by Tornhoof** [comment]
It works, but it's quite a bit of work and quite error prone, especially if you don't know anything about the types you are deserializing (e.g. your null value above, decimal vs. double, Guids etc.).
The steps are:
- obtain typeconverter: `` var converter = TypeDescriptor.GetConverter(dynamic);``
- Find out if the dynamic is a complex object by converting it to a Dictionary<string,object>
- Find out if the dynamic is an array by converting it to an array etc.
- Find out if the dynamic is a string, value types, primitve types by converting it to string etc.

And repeat that until your done, TypeConverters have a method ``CanConvertTo`` which will try the conversion without throwing an exception. This is not designed for performance e.g. CanConvertTo then doing ConvertTo basically amounts to doing the conversion twice. Personally I wouldn't try this if you don't know the types you're deserializing before hand, simply because JSON is not as typesafe as C#.

**Comment by juho-hanhimaki** [comment]
Thanks Tornhoof. I did try your suggestion and indeed I was able to get it working quite similarly as Json.NET. However the conversions via the TypeConverter absolutely ruined the performance.

**Comment by Tornhoof** [comment]
Yes, as I wrote, it does the conversion twice, if you know the types, you can skip the ``CanConvertTo`` step and it's pretty much twice as fast, but even then it's only marginally faster than JSON.NET.
