### ISSUE TITLE
Serialize has inconsistent behavior with dynamics

### ISSUE THREAD

**Issue by arnath** [kevin-montrose/Jil#305]
I've been trying JIL out with some dynamic payloads and noticed some odd behavior recently. If I do this, everything serializes correctly:

```c#
dynamic test = new { Value = new { IsTrue = true } };
string json = JSON.Serialize(test);
// Returns this: {"Value":{"IsTrue":true}}
```

However, if I do this, the dynamic field gets serialized as empty braces and I have to use SerializeDynamic for it to work:

```c#
public class DynamicTest
{
    public dynamic Value { get; set; }
}
DynamicTest test = new DynamicTest() { Value = new { IsTrue = true } };
string json = JSON.Serialize(test);
// Returns this: {"Value":{}}
````

Is this inconsistency expected? I would expect Serialize to either work or not work for both of these cases.

**Comment by arnath** [comment]
I fully understand that SerializeDynamic will correctly handle both these cases and am currently using that. 

I'm just trying to understand why these two cases are inconsistent. I would expect a dynamic field within an object to either never work if you call Serialize or work all the time if you call Serialize. Instead, it works in one case and not the other.

**Comment by Tornhoof** [comment]
Ok, let me explain it (a bit):
``dynamic`` is just syntactic sugar for the user, the type is still ``object``.
So forget all the ``dynamic`` in your example and replace it with ``object`` in your mind.

The first example is an anonymous type and Value is again an anonymous type. ``Serialize`` can generate a valid serializer for that because it's actually well defined, the "name" of the type is something like ``<>f__AnonymousType0`1[<>f__AnonymousType1`1[System.Boolean]]``, so the full type and all children's types are well known during the generation of the serializer.
Simply said, Value can't be anything else than ``<>f__AnonymousType1`1[System.Boolean]``

In your second example, the type of ``Value`` is not known at compile time, for the Serializer sees a property of type ``object`` and the concrete type needs to be decided at serialization time, and ``SerializeDynamic`` is doing exactly that, adding logic that the concrete serializer for ``Value`` is decided at runtime.

That's why both are not the same case, there is no inconsistency, the first type is fully known at serialization generation time and the second is known only at runtime.

**Comment by kevin-montrose** [comment]
This is by design, in an "all the options were kind of bad"-way.

There's a single check at the start of a Serialize<T>() call to see if <T> EXACTLY matches typeof(object), and if so it actually calls SerializeDynamic().  This addresses an earlier series of complaints, due to lots of people (incorrectly) calling Serialize<dynamic>().  This logic isn't applied anywhere else, as this was a very narrow fix for the very narrow complaint.
