### ISSUE TITLE
Can't deserialize to System.Json.JsonArray

### ISSUE THREAD

**Issue by Cephei** [kevin-montrose/Jil#307]
I'm receiving: `Expected a parameterless constructor for System.Json.JsonArray`
Any chance of adding support for deserializing to https://github.com/dotnet/corefx/blob/master/src/System.Json/src/System/Json/JsonArray.cs

I'm not too familiar with the Jil source, but it looks like modifying `InlineDeserializer` to add `IsJsonArray` - perhaps detecting `IList<JsonValue>`. 
The constructor takes a params, but supports the `Add` method.

**Comment by kevin-montrose** [comment]
If Jil detected the params constructor and used it, we'd still run into issues with JsonValue which is an abstract type.  In order to support deserializing to JsonArray, Jil would have to special case it (I guess we could detect implicit operators, but that is reaaaaally messy and I think unexpected of a (de)serializer. 

I don't hate the idea of using a params constructor, but I'm not going to make that change at this time - I need to think through the implications, and have more spare time to explore implementation.
