### ISSUE TITLE
Serializing Dictionary<string,object>

### ISSUE THREAD

**Issue by krsih** [kevin-montrose/Jil#317]
Hi,

I trying to serailize my dictionary  Dictionary<string,object>, but the value part seems to be not getting serialized, This seems to be working with newtonsoft though.

Can you please let me know if this is not supported using JIL.

 `var dicAdd = new Dictionary<string, object> {{"key2", 30}};
            using (var ms = new MemoryStream())
            using (var output = new StreamWriter(ms))
            {
                JSON.Serialize(
                    dicAdd, output
                );
                output.Flush();

                using (var fileStream = File.Create(@"C:\\temp\\2.txt"))
                {
                    ms.Seek(0, SeekOrigin.Begin);
                    ms.CopyTo(fileStream);
                }
            }`

**Comment by Wazner** [comment]
This is a common pitfall with Jil and it's because the `Serialize` method only serialises what it statically knows from the type. The `object` type doesn't contain any serialisable fields, so will serialise as `{}`.

Besides the `Serialise` method, Jil also has a `SerialiseDynamic` method. This method will look at the value to determine it's type instead of the static generic type. It ends up being a little bit slower than `Serialise` in most cases, but it's the only way to serialise downcasted values (object -> string for example).

Check out the wiki page: https://github.com/kevin-montrose/Jil/wiki/Common-Pitfalls#base-classes-as-member-types
