### ISSUE TITLE
Persisting serializers/deserializers to an assembly for better startup time

### ISSUE THREAD

**Issue by craigajohnson** [kevin-montrose/Jil#88]
This is a great library. I have a suggestion for an issue we're seeing in a production environment with a decent-sized object graph.

Here's the scenario:
- On startup, the app performs serialization/deserialization pairs on dummy object graphs (async in a Task)
- This process takes several seconds, is heavy on CPU, and memory usage climbs to over 1GB.
- Once done, most of the memory is reclaimed and serialization/deserialization performance is excellent as would be expected.

What I'd like to accomplish:
- During the build process, I want to launch a step that generates the serializers/deserializers I need and write them to an assembly.
- At runtime, I want to specify this assembly in some type of Jil initialization method. Jil would then look first to this assembly and use the prebuilt serializers/deserializers as needed.
- I will assume all risks for impedance between the object in question and the prebuilt assembly.

I can take a crack at this change and send a pull request, unless you see a problem with this request or advise against it for whatever reason. The end goal is to reduce the startup initialization time so how that's done isn't particularly important.

**Comment by Scooletz** [comment]
How about using weaver like Fody and provide a plugin which does that? Having one assembly instead of *.Serializers is better imho.

**Comment by aL3891** [comment]
I'd also like something like this, but for a slightly different use case, .net native. If you could pre-generate the serializers and put them in an assembly and then reference that, .net native would have an easier time using them.
i'd love to take a stab at it but i cant commit to a timeframe unfortunately :/

**Comment by mgravell** [comment]
The work required to do this, at the current time, is ... extensive. You
can't do it using the platform-specific builds, as many (core-clr, etc)
lack emit to dll options. You can't do it using the regular .NET 4.* build,
as IL-emit doesn't allow cross-targeting (it will reference the wrong
runtimes). The way I do it in protobuf-net is to use IKVM as a bridge, as
that has a cloned IL-emit API that permits cross-targeting... but to do
that would require a rewrite of Sigil, or the removal of Sigil completely.

In the general case, *at that point*, I'm (from bitter-sweet experience)
reaching the conclusion that the better option is C# code generation. There
aren't currently any friendly ways to deploy code-gen tools, though, if you
expect them to work in various build tools.

On 9 December 2015 at 08:41, Allan Lindqvist <notifications@github.com>
wrote:

> I'd also like something like this, but for a slightly different use case,
> .net native. If you could pre-generate the serializers and put them in an
> assembly and then reference that, .net native would have an easier time
> using them.
> i'd love to take a stab at it but i cant commit to a timeframe
> unfortunately :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevin-montrose/Jil/issues/88#issuecomment-163151237>.
>



-- 
Regards,

Marc

**Comment by aL3891** [comment]
I havent looked super closely at the code yet, but do you think it would be possible to codegen all the tricks that jil does to speed up serialization? i have my own internal hobby project were i've been thinking about codegening serializers but it hasnt really materialized into something useful and i wasn't aware of jil at the time, so i'm curious to learn from this project :)

**Comment by mgravell** [comment]
Can it be done? yes, mostly (see below)

Can it be done with the existing code: no

Code-gen is radically different to il-emit, and it would essentially be a
rewrite of the core. I'm not saying that rules it out, but it at least sets
the context.

Note also that code-gen doesn't allow *all* the tricks, because the
compiler is going to want to enforce things like accessibility rules. If
Jil currently allows access to private members (and I can't remember
whether or not it does), that won't work. Also, some of what Jil does: it
does by performing IL analysis of code that *isn't necessarily in the
current project*. For example, it actually does magic to figure out whether
the return value *from a property* is going to be constant value, and it
does analysis of things like constructors to determine intent. Those things
won't necessarily work the same, unless a way can be found to do equivalent
functionality. Core-CLR already has to make some compromises here, because
IL of other methods isn't as readily available (although I have some code I
need to try, there) - so it won't be a first. Likewise, Rosyln potentially
provides access to *much* of that info, but **only for in-project code**.

On 9 December 2015 at 15:24, Allan Lindqvist <notifications@github.com>
wrote:

> I havent looked super closely at the code yet, but do you think it would
> be possible to codegen all the tricks that jil does to speed up
> serialization? i have my own internal hobby project were i've been thinking
> about codegening serializers but it hasnt really materialized into
> something useful and i wasn't aware of jil at the time, so i'm curious to
> learn from this project :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevin-montrose/Jil/issues/88#issuecomment-163289914>.
>



-- 
Regards,

Marc
